---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-kube-app
  name: python-kube-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: python-kube-app
  template:
    metadata:
      labels:
        app: python-kube-app
      name: python-kube-app
      namespace: default
    spec:
      containers:
        - image: ghcr.io/mustafaguc/python-kube-app:latest
          imagePullPolicy: Always
          name: container-0
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: my-docker-registry
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: python-kube-app
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: python-kube-app
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-kube-app
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: python-kube-app.example.com
      http:
        paths:
          - backend:
              service:
                name: python-kube-app
                port:
                  name: http
            path: /
            pathType: Prefix